/*
 * TicketAlarm
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing AlarmDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AlarmDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AlarmDto
        //private AlarmDto instance;

        public AlarmDtoTests()
        {
            // TODO uncomment below to create an instance of AlarmDto
            //instance = new AlarmDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AlarmDto
        /// </summary>
        [Fact]
        public void AlarmDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" AlarmDto
            //Assert.IsType<AlarmDto>(instance);
        }

        /// <summary>
        /// Test the property 'IdAlarm'
        /// </summary>
        [Fact]
        public void IdAlarmTest()
        {
            // TODO unit test for the property 'IdAlarm'
        }

        /// <summary>
        /// Test the property 'IdShow'
        /// </summary>
        [Fact]
        public void IdShowTest()
        {
            // TODO unit test for the property 'IdShow'
        }

        /// <summary>
        /// Test the property 'Mail'
        /// </summary>
        [Fact]
        public void MailTest()
        {
            // TODO unit test for the property 'Mail'
        }

        /// <summary>
        /// Test the property 'Phone'
        /// </summary>
        [Fact]
        public void PhoneTest()
        {
            // TODO unit test for the property 'Phone'
        }

        /// <summary>
        /// Test the property 'DateTimeMailRequest'
        /// </summary>
        [Fact]
        public void DateTimeMailRequestTest()
        {
            // TODO unit test for the property 'DateTimeMailRequest'
        }

        /// <summary>
        /// Test the property 'DateTimeMailSent'
        /// </summary>
        [Fact]
        public void DateTimeMailSentTest()
        {
            // TODO unit test for the property 'DateTimeMailSent'
        }

        /// <summary>
        /// Test the property 'DateTimeTextRequest'
        /// </summary>
        [Fact]
        public void DateTimeTextRequestTest()
        {
            // TODO unit test for the property 'DateTimeTextRequest'
        }

        /// <summary>
        /// Test the property 'DateTimeTextSent'
        /// </summary>
        [Fact]
        public void DateTimeTextSentTest()
        {
            // TODO unit test for the property 'DateTimeTextSent'
        }
    }
}
