/*
 * TicketAlarm
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ArtistDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ArtistDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ArtistDto
        //private ArtistDto instance;

        public ArtistDtoTests()
        {
            // TODO uncomment below to create an instance of ArtistDto
            //instance = new ArtistDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ArtistDto
        /// </summary>
        [Fact]
        public void ArtistDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" ArtistDto
            //Assert.IsType<ArtistDto>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'UrlPhoto'
        /// </summary>
        [Fact]
        public void UrlPhotoTest()
        {
            // TODO unit test for the property 'UrlPhoto'
        }
    }
}
