/*
 * TicketAlarm
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing AvailabilityDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AvailabilityDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AvailabilityDto
        //private AvailabilityDto instance;

        public AvailabilityDtoTests()
        {
            // TODO uncomment below to create an instance of AvailabilityDto
            //instance = new AvailabilityDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AvailabilityDto
        /// </summary>
        [Fact]
        public void AvailabilityDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" AvailabilityDto
            //Assert.IsType<AvailabilityDto>(instance);
        }

        /// <summary>
        /// Test the property 'IdShow'
        /// </summary>
        [Fact]
        public void IdShowTest()
        {
            // TODO unit test for the property 'IdShow'
        }

        /// <summary>
        /// Test the property 'Screenshot'
        /// </summary>
        [Fact]
        public void ScreenshotTest()
        {
            // TODO unit test for the property 'Screenshot'
        }
    }
}
