/*
 * TicketAlarm
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ShowDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ShowDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ShowDto
        //private ShowDto instance;

        public ShowDtoTests()
        {
            // TODO uncomment below to create an instance of ShowDto
            //instance = new ShowDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ShowDto
        /// </summary>
        [Fact]
        public void ShowDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" ShowDto
            //Assert.IsType<ShowDto>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'IdArtist'
        /// </summary>
        [Fact]
        public void IdArtistTest()
        {
            // TODO unit test for the property 'IdArtist'
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

        /// <summary>
        /// Test the property 'DateTimeShow'
        /// </summary>
        [Fact]
        public void DateTimeShowTest()
        {
            // TODO unit test for the property 'DateTimeShow'
        }

        /// <summary>
        /// Test the property 'IdFnac'
        /// </summary>
        [Fact]
        public void IdFnacTest()
        {
            // TODO unit test for the property 'IdFnac'
        }

        /// <summary>
        /// Test the property 'City'
        /// </summary>
        [Fact]
        public void CityTest()
        {
            // TODO unit test for the property 'City'
        }

        /// <summary>
        /// Test the property 'Arena'
        /// </summary>
        [Fact]
        public void ArenaTest()
        {
            // TODO unit test for the property 'Arena'
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

        /// <summary>
        /// Test the property 'Available'
        /// </summary>
        [Fact]
        public void AvailableTest()
        {
            // TODO unit test for the property 'Available'
        }

        /// <summary>
        /// Test the property 'Artist'
        /// </summary>
        [Fact]
        public void ArtistTest()
        {
            // TODO unit test for the property 'Artist'
        }
    }
}
