/*
 * TicketAlarm
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// AlarmDto
    /// </summary>
    [DataContract(Name = "AlarmDto")]
    public partial class AlarmDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AlarmDto" /> class.
        /// </summary>
        /// <param name="idAlarm">idAlarm.</param>
        /// <param name="idShow">idShow.</param>
        /// <param name="mail">mail.</param>
        /// <param name="phone">phone.</param>
        /// <param name="dateTimeMailRequest">dateTimeMailRequest.</param>
        /// <param name="dateTimeMailSent">dateTimeMailSent.</param>
        /// <param name="dateTimeTextRequest">dateTimeTextRequest.</param>
        /// <param name="dateTimeTextSent">dateTimeTextSent.</param>
        public AlarmDto(int idAlarm = default(int), int idShow = default(int), string mail = default(string), string phone = default(string), DateTime? dateTimeMailRequest = default(DateTime?), DateTime? dateTimeMailSent = default(DateTime?), DateTime? dateTimeTextRequest = default(DateTime?), DateTime? dateTimeTextSent = default(DateTime?))
        {
            this.IdAlarm = idAlarm;
            this.IdShow = idShow;
            this.Mail = mail;
            this.Phone = phone;
            this.DateTimeMailRequest = dateTimeMailRequest;
            this.DateTimeMailSent = dateTimeMailSent;
            this.DateTimeTextRequest = dateTimeTextRequest;
            this.DateTimeTextSent = dateTimeTextSent;
        }

        /// <summary>
        /// Gets or Sets IdAlarm
        /// </summary>
        [DataMember(Name = "idAlarm", EmitDefaultValue = false)]
        public int IdAlarm { get; set; }

        /// <summary>
        /// Gets or Sets IdShow
        /// </summary>
        [DataMember(Name = "idShow", EmitDefaultValue = false)]
        public int IdShow { get; set; }

        /// <summary>
        /// Gets or Sets Mail
        /// </summary>
        [DataMember(Name = "mail", EmitDefaultValue = true)]
        public string Mail { get; set; }

        /// <summary>
        /// Gets or Sets Phone
        /// </summary>
        [DataMember(Name = "phone", EmitDefaultValue = true)]
        public string Phone { get; set; }

        /// <summary>
        /// Gets or Sets DateTimeMailRequest
        /// </summary>
        [DataMember(Name = "dateTimeMailRequest", EmitDefaultValue = true)]
        public DateTime? DateTimeMailRequest { get; set; }

        /// <summary>
        /// Gets or Sets DateTimeMailSent
        /// </summary>
        [DataMember(Name = "dateTimeMailSent", EmitDefaultValue = true)]
        public DateTime? DateTimeMailSent { get; set; }

        /// <summary>
        /// Gets or Sets DateTimeTextRequest
        /// </summary>
        [DataMember(Name = "dateTimeTextRequest", EmitDefaultValue = true)]
        public DateTime? DateTimeTextRequest { get; set; }

        /// <summary>
        /// Gets or Sets DateTimeTextSent
        /// </summary>
        [DataMember(Name = "dateTimeTextSent", EmitDefaultValue = true)]
        public DateTime? DateTimeTextSent { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AlarmDto {\n");
            sb.Append("  IdAlarm: ").Append(IdAlarm).Append("\n");
            sb.Append("  IdShow: ").Append(IdShow).Append("\n");
            sb.Append("  Mail: ").Append(Mail).Append("\n");
            sb.Append("  Phone: ").Append(Phone).Append("\n");
            sb.Append("  DateTimeMailRequest: ").Append(DateTimeMailRequest).Append("\n");
            sb.Append("  DateTimeMailSent: ").Append(DateTimeMailSent).Append("\n");
            sb.Append("  DateTimeTextRequest: ").Append(DateTimeTextRequest).Append("\n");
            sb.Append("  DateTimeTextSent: ").Append(DateTimeTextSent).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
