/*
 * TicketAlarm.API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// AvailabilityDto
    /// </summary>
    [DataContract(Name = "AvailabilityDto")]
    public partial class AvailabilityDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AvailabilityDto" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="idShow">idShow.</param>
        /// <param name="dateTimeAvailability">dateTimeAvailability.</param>
        public AvailabilityDto(int id = default(int), int idShow = default(int), DateTime dateTimeAvailability = default(DateTime))
        {
            this.Id = id;
            this.IdShow = idShow;
            this.DateTimeAvailability = dateTimeAvailability;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public int Id { get; set; }

        /// <summary>
        /// Gets or Sets IdShow
        /// </summary>
        [DataMember(Name = "idShow", EmitDefaultValue = false)]
        public int IdShow { get; set; }

        /// <summary>
        /// Gets or Sets DateTimeAvailability
        /// </summary>
        [DataMember(Name = "dateTimeAvailability", EmitDefaultValue = false)]
        public DateTime DateTimeAvailability { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AvailabilityDto {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  IdShow: ").Append(IdShow).Append("\n");
            sb.Append("  DateTimeAvailability: ").Append(DateTimeAvailability).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
