/**
 * TicketAlarm
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ArtistDto model module.
 * @module model/ArtistDto
 * @version v1
 */
class ArtistDto {
    /**
     * Constructs a new <code>ArtistDto</code>.
     * @alias module:model/ArtistDto
     */
    constructor() { 
        
        ArtistDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ArtistDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ArtistDto} obj Optional instance to populate.
     * @return {module:model/ArtistDto} The populated <code>ArtistDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ArtistDto();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('urlPhoto')) {
                obj['urlPhoto'] = ApiClient.convertToType(data['urlPhoto'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ArtistDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ArtistDto</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['urlPhoto'] && !(typeof data['urlPhoto'] === 'string' || data['urlPhoto'] instanceof String)) {
            throw new Error("Expected the field `urlPhoto` to be a primitive type in the JSON string but got " + data['urlPhoto']);
        }

        return true;
    }


}



/**
 * @member {String} name
 */
ArtistDto.prototype['name'] = undefined;

/**
 * @member {String} urlPhoto
 */
ArtistDto.prototype['urlPhoto'] = undefined;






export default ArtistDto;

