/*
 * TicketAlarm
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing ArtistApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ArtistApiTests : IDisposable
    {
        private ArtistApi instance;

        public ArtistApiTests()
        {
            instance = new ArtistApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ArtistApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ArtistApi
            //Assert.IsType<ArtistApi>(instance);
        }

        /// <summary>
        /// Test ApiArtistsGet
        /// </summary>
        [Fact]
        public void ApiArtistsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ApiArtistsGet();
            //Assert.IsType<List<ArtistDto>>(response);
        }

        /// <summary>
        /// Test ApiArtistsPost
        /// </summary>
        [Fact]
        public void ApiArtistsPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ArtistDto? artistDto = null;
            //var response = instance.ApiArtistsPost(artistDto);
            //Assert.IsType<int>(response);
        }
    }
}
