/*
 * TicketAlarm
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing EmailApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class EmailApiTests : IDisposable
    {
        private EmailApi instance;

        public EmailApiTests()
        {
            instance = new EmailApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EmailApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' EmailApi
            //Assert.IsType<EmailApi>(instance);
        }

        /// <summary>
        /// Test ApiEmailPost
        /// </summary>
        [Fact]
        public void ApiEmailPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //AlarmDto? alarmDto = null;
            //var response = instance.ApiEmailPost(alarmDto);
            //Assert.IsType<int>(response);
        }
    }
}
