/*
 * TicketAlarm
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing ShowApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ShowApiTests : IDisposable
    {
        private ShowApi instance;

        public ShowApiTests()
        {
            instance = new ShowApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ShowApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ShowApi
            //Assert.IsType<ShowApi>(instance);
        }

        /// <summary>
        /// Test ApiShowsGet
        /// </summary>
        [Fact]
        public void ApiShowsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //bool? active = null;
            //var response = instance.ApiShowsGet(active);
            //Assert.IsType<List<ShowDto>>(response);
        }

        /// <summary>
        /// Test ApiShowsIdShowGet
        /// </summary>
        [Fact]
        public void ApiShowsIdShowGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int idShow = null;
            //var response = instance.ApiShowsIdShowGet(idShow);
            //Assert.IsType<ShowDto>(response);
        }

        /// <summary>
        /// Test ApiShowsIdShowPut
        /// </summary>
        [Fact]
        public void ApiShowsIdShowPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int idShow = null;
            //ShowDto? showDto = null;
            //var response = instance.ApiShowsIdShowPut(idShow, showDto);
            //Assert.IsType<ShowDto>(response);
        }

        /// <summary>
        /// Test ApiShowsPost
        /// </summary>
        [Fact]
        public void ApiShowsPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ShowDto? showDto = null;
            //var response = instance.ApiShowsPost(showDto);
            //Assert.IsType<int>(response);
        }
    }
}
