/**
 * TicketAlarm
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AlarmDto { 
    idAlarm?: number;
    idShow?: number;
    mail?: string | null;
    phone?: string | null;
    dateTimeMailRequest?: string | null;
    dateTimeMailSent?: string | null;
    dateTimeTextRequest?: string | null;
    dateTimeTextSent?: string | null;
}

