/**
 * TicketAlarm
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BaseShowDto } from './baseShowDto';


export interface ArtistDto { 
    name?: string | null;
    urlPhoto?: string | null;
    shows?: Array<BaseShowDto> | null;
}

