/**
 * TicketAlarm
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BaseShowDto { 
    id?: number;
    idArtist?: number;
    title?: string | null;
    dateTimeShow?: string;
    idFnac?: number;
    city?: string | null;
    arena?: string | null;
    url?: string | null;
    available?: boolean;
}

