/**
 * TicketAlarm
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BaseArtistDto } from './baseArtistDto';


export interface ShowDto { 
    id?: number;
    idArtist?: number;
    title?: string | null;
    dateTimeShow?: string;
    idFnac?: number;
    city?: string | null;
    arena?: string | null;
    url?: string | null;
    available?: boolean;
    artist?: BaseArtistDto;
}

