/**
 * TicketAlarm
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TicketAlarm);
  }
}(this, function(expect, TicketAlarm) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TicketAlarm.AlarmDto();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AlarmDto', function() {
    it('should create an instance of AlarmDto', function() {
      // uncomment below and update the code to test AlarmDto
      //var instance = new TicketAlarm.AlarmDto();
      //expect(instance).to.be.a(TicketAlarm.AlarmDto);
    });

    it('should have the property idAlarm (base name: "idAlarm")', function() {
      // uncomment below and update the code to test the property idAlarm
      //var instance = new TicketAlarm.AlarmDto();
      //expect(instance).to.be();
    });

    it('should have the property idShow (base name: "idShow")', function() {
      // uncomment below and update the code to test the property idShow
      //var instance = new TicketAlarm.AlarmDto();
      //expect(instance).to.be();
    });

    it('should have the property mail (base name: "mail")', function() {
      // uncomment below and update the code to test the property mail
      //var instance = new TicketAlarm.AlarmDto();
      //expect(instance).to.be();
    });

    it('should have the property phone (base name: "phone")', function() {
      // uncomment below and update the code to test the property phone
      //var instance = new TicketAlarm.AlarmDto();
      //expect(instance).to.be();
    });

    it('should have the property dateTimeMailRequest (base name: "dateTimeMailRequest")', function() {
      // uncomment below and update the code to test the property dateTimeMailRequest
      //var instance = new TicketAlarm.AlarmDto();
      //expect(instance).to.be();
    });

    it('should have the property dateTimeMailSent (base name: "dateTimeMailSent")', function() {
      // uncomment below and update the code to test the property dateTimeMailSent
      //var instance = new TicketAlarm.AlarmDto();
      //expect(instance).to.be();
    });

    it('should have the property dateTimeTextRequest (base name: "dateTimeTextRequest")', function() {
      // uncomment below and update the code to test the property dateTimeTextRequest
      //var instance = new TicketAlarm.AlarmDto();
      //expect(instance).to.be();
    });

    it('should have the property dateTimeTextSent (base name: "dateTimeTextSent")', function() {
      // uncomment below and update the code to test the property dateTimeTextSent
      //var instance = new TicketAlarm.AlarmDto();
      //expect(instance).to.be();
    });

  });

}));
