/**
 * TicketAlarm
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AlarmDto model module.
 * @module model/AlarmDto
 * @version v1
 */
class AlarmDto {
    /**
     * Constructs a new <code>AlarmDto</code>.
     * @alias module:model/AlarmDto
     */
    constructor() { 
        
        AlarmDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AlarmDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AlarmDto} obj Optional instance to populate.
     * @return {module:model/AlarmDto} The populated <code>AlarmDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AlarmDto();

            if (data.hasOwnProperty('idAlarm')) {
                obj['idAlarm'] = ApiClient.convertToType(data['idAlarm'], 'Number');
            }
            if (data.hasOwnProperty('idShow')) {
                obj['idShow'] = ApiClient.convertToType(data['idShow'], 'Number');
            }
            if (data.hasOwnProperty('mail')) {
                obj['mail'] = ApiClient.convertToType(data['mail'], 'String');
            }
            if (data.hasOwnProperty('phone')) {
                obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
            }
            if (data.hasOwnProperty('dateTimeMailRequest')) {
                obj['dateTimeMailRequest'] = ApiClient.convertToType(data['dateTimeMailRequest'], 'Date');
            }
            if (data.hasOwnProperty('dateTimeMailSent')) {
                obj['dateTimeMailSent'] = ApiClient.convertToType(data['dateTimeMailSent'], 'Date');
            }
            if (data.hasOwnProperty('dateTimeTextRequest')) {
                obj['dateTimeTextRequest'] = ApiClient.convertToType(data['dateTimeTextRequest'], 'Date');
            }
            if (data.hasOwnProperty('dateTimeTextSent')) {
                obj['dateTimeTextSent'] = ApiClient.convertToType(data['dateTimeTextSent'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AlarmDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AlarmDto</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['mail'] && !(typeof data['mail'] === 'string' || data['mail'] instanceof String)) {
            throw new Error("Expected the field `mail` to be a primitive type in the JSON string but got " + data['mail']);
        }
        // ensure the json data is a string
        if (data['phone'] && !(typeof data['phone'] === 'string' || data['phone'] instanceof String)) {
            throw new Error("Expected the field `phone` to be a primitive type in the JSON string but got " + data['phone']);
        }

        return true;
    }


}



/**
 * @member {Number} idAlarm
 */
AlarmDto.prototype['idAlarm'] = undefined;

/**
 * @member {Number} idShow
 */
AlarmDto.prototype['idShow'] = undefined;

/**
 * @member {String} mail
 */
AlarmDto.prototype['mail'] = undefined;

/**
 * @member {String} phone
 */
AlarmDto.prototype['phone'] = undefined;

/**
 * @member {Date} dateTimeMailRequest
 */
AlarmDto.prototype['dateTimeMailRequest'] = undefined;

/**
 * @member {Date} dateTimeMailSent
 */
AlarmDto.prototype['dateTimeMailSent'] = undefined;

/**
 * @member {Date} dateTimeTextRequest
 */
AlarmDto.prototype['dateTimeTextRequest'] = undefined;

/**
 * @member {Date} dateTimeTextSent
 */
AlarmDto.prototype['dateTimeTextSent'] = undefined;






export default AlarmDto;

